name: seeya
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  #device functionality
#  multi_image_picker: ^4.7.15
#  image_cropper: ^1.3.1
  permission_handler: ^5.1.0+2
#  path_provider: ^1.6.27
#  xfile: ^1.1.0
  intl: any



#  camerawesome: ^0.1.2+1
  camera: ^0.7.0
  stream_chat_flutter: ^1.3.2-beta
  dio: ^3.0.10
  lottie: ^0.7.0+1
  animated_text_kit: ^4.1.1
  flutter_spinkit: ^5.0.0
  loading_overlay: ^0.3.0
  graphql_flutter: ^4.0.0-alpha.3

  #Get
  get_storage: ^1.4.0
  get: ^3.15.0

  #UI/UX
  flutter_typeahead: ^2.0.0
  bottom_drawer: ^0.0.2
  flutter_feather_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  animated_bottom_navigation_bar: ^0.3.2
  buttons_tabbar: ^1.1.1

  flutter_svg: ^0.19.3
  #map
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.0
  geocoder: ^0.2.1
  location: 3.2.4

  #image
#  image_picker: ^0.6.7+22
  cached_network_image: ^2.5.0

  #debugging
  logger : any


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Stag
      fonts:
        - asset: fonts/Stag-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
